services:
  local-postgres:
    image: postgres:16-alpine
    container_name: local-postgres
    restart: unless-stopped
    ports:
      - "5701:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: design_system
    volumes:
      - local-postgres-data:/var/lib/postgresql/data

volumes:
  local-postgres-data:
