export const videos = [
  {
    id: 'v1',
    prompt: 'Weathered hands of an artisan stitching a saddle in a sunlit Paris atelier, dust motes drifting through amber afternoon light',
    status: 'done',
    imageUsed: false,
    thumbnailUrl: null,
    videoUrl: '/assets/placeholder.mp4',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'v2',
    prompt: 'A silk scarf unfolds in slow motion against a pale grey sky, catching the last light of a winter dusk over the Seine',
    status: 'done',
    imageUsed: true,
    thumbnailUrl: null,
    videoUrl: '/assets/placeholder.mp4',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'v3',
    prompt: 'Dense morning fog rolls across an empty Norman countryside road, a lone chestnut stallion standing still at the edge of a stone fence',
    status: 'done',
    imageUsed: false,
    thumbnailUrl: null,
    videoUrl: '/assets/placeholder.mp4',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'v4',
    prompt: 'Pale winter light filters through tall workshop windows, casting long shadows across rows of hand-stitched leather bags on a oak workbench',
    status: 'done',
    imageUsed: true,
    thumbnailUrl: null,
    videoUrl: '/assets/placeholder.mp4',
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 'v5',
    prompt: 'A rider in a long coat canters through golden meadow grass at dusk, bridle catching the fading copper light as mist gathers at the treeline',
    status: 'done',
    imageUsed: false,
    thumbnailUrl: null,
    videoUrl: '/assets/placeholder.mp4',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'v6',
    prompt: 'Close-up of a craftsman\'s knife tracing the edge of vegetable-tanned leather on a worn cutting table, shavings curling away in the still air of a quiet atelier',
    status: 'done',
    imageUsed: true,
    thumbnailUrl: null,
    videoUrl: '/assets/placeholder.mp4',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
];
