import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'bg-hero': 'var(--color-bg-hero)',
        'brand-primary': 'var(--color-brand-primary)',
        'text-on-dark': 'var(--color-text-on-dark)',
        'section-bg-light': 'var(--color-section-bg-light)',
        'text-heading': 'var(--color-text-heading)',
        'text-body': 'var(--color-text-body)',
        'card-bg': 'var(--color-card-bg)',
        'accent-blue': 'var(--color-accent-blue)',
        'nav-border': 'var(--color-nav-border)',
        'logo-on-light': 'var(--color-logo-on-light)',
        'text-ui': 'var(--color-text-ui)',
        'text-meta': 'var(--color-text-meta)',
        'content-panel-bg': 'var(--color-content-panel-bg)',
        'content-panel-border': 'var(--color-content-panel-border)',
        'page-bg-dark': 'var(--color-page-bg-dark)',
        'text-primary-dark': 'var(--color-text-primary-dark)',
        'text-secondary-dark': 'var(--color-text-secondary-dark)',
        'brand-green-dark': 'var(--color-brand-green-dark)',
        'dark-green-bg': 'var(--color-dark-green-bg)',
        'surface-dark': 'var(--color-surface-dark)',
        'surface-dark-deep': 'var(--color-surface-dark-deep)',
        'card-border-dark': 'var(--color-card-border-dark)',
        'text-body-dark': 'var(--color-text-body-dark)',
        'divider': 'var(--color-divider)',
        'progress-track': 'var(--color-progress-track)',
        'avatar-gradient-start': 'var(--color-avatar-gradient-start)',
        'avatar-gradient-end': 'var(--color-avatar-gradient-end)',
        'text-muted': 'var(--color-text-muted)',
        'overlay-dim': 'var(--color-overlay-dim)',
      },
      fontFamily: {
        display: ['Helvetica Neue', 'Arial', 'sans-serif'],
        body: ['Inter Variable', 'Inter', 'sans-serif'],
        logo: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['80px', { lineHeight: '88.32px', letterSpacing: '-3.6px' }],
        'section-heading': ['49px', { lineHeight: '57.2px', letterSpacing: '-1.2px' }],
        'card-heading': ['30px', { lineHeight: 'normal', letterSpacing: '-0.2px' }],
        'section-body': ['22px', { lineHeight: '30.8px', letterSpacing: '-0.3px' }],
        'btn': ['18px', { lineHeight: '24px', letterSpacing: '-0.18px' }],
        'nav': ['16px', { letterSpacing: 'normal' }],
        'meta': ['14px', { letterSpacing: '-0.15px' }],
        'eyebrow': ['13px', { letterSpacing: '0.8px' }],
        'tab': ['32px', { letterSpacing: '-0.2px' }],
      },
      spacing: {
        'nav-h': 'var(--nav-height)',
        'nav-px': 'var(--nav-padding-inline)',
        'nav-gap': 'var(--nav-gap)',
        'btn-block': 'var(--btn-padding-block)',
        'btn-inline': 'var(--btn-padding-inline)',
        'partners-margin': 'var(--partners-page-margin)',
        'opux-section-block': 'var(--opux-section-padding-block)',
        'opux-section-inline': 'var(--opux-section-padding-inline)',
        'opux-card-pt': 'var(--opux-card-padding-top)',
        'opux-wrapper-mx': 'var(--opux-wrapper-margin-inline)',
      },
      borderRadius: {
        'btn': 'var(--btn-border-radius)',
        'card': 'var(--opux-card-radius)',
        'container': 'var(--opux-container-radius)',
        'tab-bar': 'var(--tab-bar-radius)',
        'content-panel': 'var(--content-panel-radius)',
      },
      maxWidth: {
        'container': 'var(--grid-max-width)',
        'content-section': '925px',
        'body-copy': '785px',
        'blog-column': '680px',
      },
      transitionTimingFunction: {
        'material': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        'fast': '200ms',
        'base': '300ms',
      },
    },
  },
  plugins: [],
};

export default config;
